apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Trivy - Scan local filesystem'
description: 'Trivy - Scan local filesystem'

inputs:
  path:
    description: 'The path to scan'
    default: .
  severity:
    description: 'Severities of security issues to be displayed'
    default: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  format:
    description: 'format (table,json,template,sarif,cyclonedx,spdx,spdx-json,github,cosign-vuln)'
    default: table
  
runs:
  using: composite
  steps:
    - id: trivy
      name: Scan local filesystem with Trivy
      uses: docker://darinpope/trivy:0.47.0
      shell: sh
      run: |
        whoami
        trivy fs --severity ${{ inputs.severity }} --format ${{ inputs.format }} ${{ inputs.path }}